// Icon sets with multiple images per icon
const infoIcon = 'icons/information.png';

const iconSets = {
  1: [
    'icons/female-male.png',
    'icons/female.png',
    infoIcon,
    '',
  ],
  2: [
    'icons/calendar.png',
    infoIcon,
    '',
  ],
  3: [
    'icons/gender.png',
    infoIcon,
    '',
  ],
  4: [
    'icons/practice.png',
    infoIcon,
    '',
  ]
};

// 3 categories: atmosphere, labor, birth
const defaultImages = [
  {
    id:1,
    category: 'labor',
    src: 'img/ECG-op-rug_ECG-on-back.png',
    title: 'ECG op rug',
    description: 'De hartslag van de baby wordt continu gemeten met een ECG op de rug van de moeder.',
  },
  {
    id:2,
    category: 'atmosphere',
    src: 'img/aromatherapie.png',
    title: 'Aromatherapie',
    description: 'Aromatherapie wordt toegepast om de bevalling te ondersteunen.',
  },
  {
    id:3,
    category: 'labor',
    src: 'img/baarkruk_birthing-stool.png',
    title: 'Baarkruk',
    description: 'De baarkruk wordt gebruikt om in een verticale positie te bevallen.',
  },
  {
    id:4,
    category: 'birth',
    src: 'img/baby-bij-partner.png',
    title: 'Baby bij partner',
    description: 'De baby wordt direct na de geboorte bij de partner gelegd.',
  },
  {
    id:5,
    category: 'birth',
    src: 'img/baby-niet-wassen_delayed-bathing.png',
    title: 'Baby niet wassen',
    description: 'De baby wordt niet direct gewassen na de geboorte.',
  },
  {
    id:6,
    category: 'birth',
    src: 'img/baby-zelf-aanpakken_catch-baby.png',
    title: 'Baby zelf aanpakken',
    description: 'De moeder pakt de baby zelf aan na de geboorte.',
  },
  {
    id:7,
    category: 'labor',
    src: 'img/badbevalling.png',
    title: 'Badbevalling',
    description: 'De bevalling vindt plaats in bad.',
  },
  {
    id:8,
    category: 'birth',
    src: 'img/bedankt.png',
    title: 'Bedankt',
    description: 'Bedankt voor de goede zorgen.',
  },
  {
    id:9,
    category: 'labor',
    src: 'img/bekkeninstabiliteit.png',
    title: 'Bekkeninstabiliteit',
    description: 'De moeder heeft bekkeninstabiliteit.',
  },
  {
    id:10,
    category: 'birth',
    src: 'img/borstvoeding_nursing.png',
    title: 'Borstvoeding',
    description: 'De baby wordt direct na de geboorte aangelegd voor borstvoeding.',
  },
  {
    id:11,
    category: 'atmosphere',
    src: 'img/breekbaar.png',
    title: 'Breekbaar',
    description: 'De moeder is breekbaar.',
  },
  {
    id:12,
    category: 'atmosphere',
    src: 'img/bubbel.png',
    title: 'Bubbel',
    description: 'Creëer een rustige bubbel om de bevalling heen.',
  },
  {
    id:13,
    category: 'birth',
    src: 'img/contactgegevens_contact-details.png',
    title: 'Contactgegevens',
    description: '.',
  },
  {
    id:14,
    category: 'birth',
    src: 'img/cordring.png',
    title: 'Cordring',
    description: 'De navelstreng wordt afgebonden met een cordring.',
  },
  {
    id:15,
    category: 'labor',
    src: 'img/douchen-bad_shower-bath.png',
    title: 'Douchen/bad',
    description: 'De moeder doucht of neemt een bad tijdens de bevalling.',
  },
  {
    id:16,
    category: 'atmosphere',
    src: 'img/doula-vroedvrouw-midwife.png',
    title: 'Doula/vroedvrouw',
    description: 'De doula of vroedvrouw ondersteunt de moeder tijdens de bevalling.',
  },
  {
    id:17,
    category: 'atmosphere',
    src: 'img/eigen-muziek.png',
    title: 'Eigen muziek',
    description: 'De moeder luistert naar haar eigen muziek tijdens de bevalling.',
  },
  {
    id:18,
    category: 'atmosphere',
    src: 'img/eigen-ritme_own-pace.png',
    title: 'Eigen ritme',
    description: 'De moeder bepaalt haar eigen ritme tijdens de bevalling.',
  },
  {
    id:19,
    category: 'labor',
    src: 'img/epidurale.png',
    title: 'Epidurale',
    description: 'De moeder krijgt een epidurale verdoving.',
  },
  {
    id:20,
    category: 'atmosphere',
    src: 'img/eten-drinken_eat-drink.png',
    title: 'Eten/drinken',
    description: 'De moeder eet en drinkt tijdens de bevalling.',
  },
  {
    id:21,
    category: 'birth',
    src: 'img/flesvoeding_bottle.png',
    title: 'Flesvoeding',
    description: 'De baby krijgt flesvoeding.',
  },
  {
    id:22,
    category: 'birth',
    src: 'img/fopspeen_pacifier.png',
    title: 'Fopspeen',
    description: 'De baby krijgt een fopspeen.',
  },
  {
    id:23,
    category: 'atmosphere',
    src: 'img/fotos.png',
    title: 'Foto\'s',
    description: 'Er worden foto\'s gemaakt tijdens de bevalling.',
  },
  {
    id:24,
    category: 'atmosphere',
    src: 'img/gedimd-licht.png',
    title: 'Gedimd licht',
    description: 'Er is gedimd licht tijdens de bevalling.',
  },
  {
    id:25,
    category: 'birth',
    src: 'img/geen-flesvoeding_no-bottle.png',
    title: 'Geen flesvoeding',
    description: 'De baby krijgt geen flesvoeding.',
  },
  {
    id:26,
    category: 'birth',
    src: 'img/geen-fopspeen_no-pacifier.png',
    title: 'Geen fopspeen',
    description: 'De baby krijgt geen fopspeen.',
  },
  {
    id:27,
    category: 'birth',
    src: 'img/geen-mutsje_no-hat.png',
    title: 'Geen mutsje',
    description: 'De baby krijgt geen mutsje op.',
  },
  {
    id:28,
    category: 'atmosphere',
    src: 'img/geen-verstoringen.png',
    title: 'Geen verstoringen',
    description: 'Er zijn geen onnodige verstoringen tijdens de bevalling.',
  },
  {
    id:29,
    category: 'labor',
    src: 'img/geen-vliezen-breken_no-rupture-membranes.png',
    title: 'Geen vliezen breken',
    description: 'De vliezen worden niet kunstmatig gebroken.',
  },
  {
    id:30,
    category: 'labor',
    src: 'img/geen-weeenopwekkers_no-oxytocin.png',
    title: 'Geen weeën opwekkers',
    description: 'Er worden geen weeën opwekkers toegediend.',
  },
  {
    id:31,
    category: 'labor',
    src: 'img/geen_no-epidurale.png',
    title: 'Geen epidurale',
    description: 'De moeder krijgt geen epidurale verdoving.',
  },
  {
    id:32,
    category: 'labor',
    src: 'img/geen_no-episiotomie.png',
    title: 'Geen episiotomie',
    description: 'Er wordt geen knip gezet.',
  },
  {
    id:33,
    category: 'birth',
    src: 'img/geen_no-vitamineK.png',
    title: 'Geen vitamine K',
    description: 'De baby krijgt geen vitamine K toegediend.',
  },
  {
    id:34,
    category: 'labor',
    src: 'img/gentle-sectio.png',
    title: 'Gentle sectio',
    description: 'Er wordt een gentle sectio uitgevoerd.',
  },
  {
    id:35,
    category: 'atmosphere',
    src: 'img/gezin-dochter-vbac.png',
    title: 'Gezin betrokken',
    description: 'Het gezin wordt betrokken bij de bevalling.',
  },
  {
    id:37,
    category: 'atmosphere',
    src: 'img/hands-off.png',
    title: 'Hands off',
    description: 'De moeder wordt met rust gelaten en mag zelf bepalen hoe ze de bevalling wil ervaren.',
  },
  {
    id:38,
    category: 'atmosphere',
    src: 'img/hands-on.png',
    title: 'Hands on',
    description: 'De moeder wordt actief begeleid tijdens de bevalling.',
  },
  {
    id:39,
    category: 'birth',
    src: 'img/huid-op-huid_skin-to-skin-2.png',
    title: 'Huid op huid',
    description: 'De baby wordt direct na de geboorte op de blote huid van de moeder gelegd.',
  },
  {
    id:41,
    category: 'atmosphere',
    src: 'img/hypnobirthing.png',
    title: 'Hypnobirthing',
    description: 'De moeder past hypnobirthing toe tijdens de bevalling.',
  },
  {
    id:42,
    category: 'labor',
    src: 'img/keizersnede_c-section.png',
    title: 'Keizersnede',
    description: 'Er wordt een keizersnede uitgevoerd.',
  },
  {
    id:43,
    category: 'birth',
    src: 'img/lotus.png',
    title: 'Lotus',
    description: 'De placenta wordt aan de baby gelaten tot deze vanzelf loslaat.',
  },
  {
    id:44,
    category: 'atmosphere',
    src: 'img/minimale-monitoring.png',
    title: 'Minimale monitoring',
    description: 'Er wordt zo min mogelijk gecontroleerd tijdens de bevalling.',
  },
  {
    id:45,
    category: 'birth',
    src: 'img/navelstreng-uitkloppen_delayed-clamping.png',
    title: 'Navelstreng uitkloppen',
    description: 'De navelstreng wordt uitgeklopt voordat deze wordt afgebonden.',
  },
  {
    id:46,
    category: 'atmosphere',
    src: 'img/niet-geen_no.png',
    title: 'Niet geen',
    description: 'De moeder wil niet dat er geen ... gebeurt.',
  },
  {
    id:47,
    category: 'atmosphere',
    src: 'img/persen-eigen-ritme_I-decide-when-to-push-2.png',
    title: 'Persen eigen ritme',
    description: 'De moeder bepaalt wanneer ze perst.',
  },
  {
    id:49,
    category: 'labor',
    src: 'img/pijnbestrijding-TENS_pain-relief.png',
    title: 'Pijnbestrijding TENS',
    description: 'De moeder maakt gebruik van pijnbestrijding met TENS.',
  },
  {
    id:50,
    category: 'birth',
    src: 'img/placenta-bewaren_keep.png',
    title: 'Placenta bewaren',
    description: 'De placenta wordt bewaard.',
  },
  {
    id:51,
    category: 'atmosphere',
    src: 'img/steeds-overleg-en-verduidelijken.png',
    title: 'Steeds overleg en verduidelijken',
    description: 'Er wordt steeds overlegd en verduidelijkt wat er gebeurt.',
  },
  {
    id:52,
    category: 'atmosphere',
    src: 'img/thuis.png',
    title: 'Thuis',
    description: 'De bevalling vindt thuis plaats.',
  },
  {
    id:53,
    category: 'birth',
    src: 'img/tijd-voor-placenta_placenta-comes-naturally.png',
    title: 'Tijd voor placenta',
    description: 'Er is voldoende tijd voor de placenta om vanzelf te komen.',
  },
  {
    id:54,
    category: 'atmosphere',
    src: 'img/tolk-nodig_need-interpreter.png',
    title: 'Tolk nodig',
    description: 'Er is een tolk nodig.',
  },
  {
    id:55,
    category: 'labor',
    src: 'img/vaginaal-onderzoek-beperken.png',
    title: 'Vaginaal onderzoek beperken',
    description: 'Er wordt zo min mogelijk vaginaal onderzoek gedaan.',
  },
  {
    id:56,
    category: 'labor',
    src: 'img/vertikale-positie_vertical-position.png',
    title: 'Vertikale positie',
    description: 'De moeder bevindt zich in een vertikale positie tijdens de bevalling.',
  },
  {
    id:57,
    category: 'labor',
    src: 'img/vliezen-breken_rupture-membranes.png',
    title: 'Vliezen breken',
    description: 'De vliezen worden kunstmatig gebroken.',
  },
  {
    id:58,
    category: 'atmosphere',
    src: 'img/vrij-bewegen_freedom-to-move.png',
    title: 'Vrij bewegen',
    description: 'De moeder heeft de vrijheid om te bewegen tijdens de bevalling.',
  },
  {
    id:59,
    category: 'labor',
    src: 'img/weeenopwekkers_oxytocin.png',
    title: 'Weeën opwekkers',
    description: 'Er worden weeën opwekkers toegediend.',
  },
  {
    id:60,
    category: 'atmosphere',
    src: 'img/weinig-personeel.png',
    title: 'Weinig personeel',
    description: 'Er is weinig personeel aanwezig tijdens de bevalling.',
  },
  {
    id:61,
    category: 'atmosphere',
    src: 'img/ziekenhuis.png',
    title: 'Ziekenhuis',
    description: 'De bevalling vindt plaats in het ziekenhuis.',
  }
];
